### PR TITLE
Add "TZ" variable for correct timezone reporting

### PR DESCRIPTION
**Pull request by FroggyFlox**
For convenience, the correct timezone can be reported in the system logs with the use of the "TZ" environment variable.

### CODE REVIEW

**Comment by alazare619** [comment]
after token index: 4 you are missing a },
also by default it will use whatever time zone your rockstor is set to. I.E. mine shows America\Chicago

**Comment by FroggyFlox** [comment]
Thanks for the information, I didn't notice it would use the system's timezone... I guess that's why `/etc/localtime` is bound, am I correct?
In this case it may be easier to keep it the way you had it.

**Comment by alazare619** [comment]
I cant particullary speak about that on other systems its just all my
containers do infact use the /etc/localtime inspecting with portainer and
such so I'm guessing rockstor does something special with it

**Comment by FroggyFlox** [comment]
Even though it is late, I simply wanted to clean up this and confirm that you were right: Rockstor does automatically mount the system's `/etc/localtime` for each rockon so specifying TZ is unnecessary. See the [correspond lines](https://github.com/rockstor/rockstor-core/blob/af0dc8680dde6b5419a5c3aec56dcf0c8d595ae0/src/rockstor/storageadmin/views/rockon_helpers.py#L179-L187) below:
```
def vol_ops(container):
    ops_list = []
    for v in DVolume.objects.filter(container=container):
        share_mnt = ('%s%s' % (settings.MNT_PT, v.share.name))
        mount_share(v.share, share_mnt)
        ops_list.extend(['-v', '%s:%s' % (share_mnt, v.dest_dir)])
    # map /etc/localtime for consistency across base rockstor and apps.
    ops_list.extend(['-v', '/etc/localtime:/etc/localtime:ro'])
    return ops_list
```

**Pull request closed without merging**
